[project]
name = "autorot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.169.0",
    "google-auth-oauthlib>=1.2.2",
    "matplotlib>=3.10.3",
    "moviepy>=2.1.2",
    "numpy>=2.2.6",
]
